[tool.autohooks]
mode = "poetry"
pre-commit = ["autohooks.plugins.black", "autohooks.plugins.pylint", "autohooks.plugins.isort"]

[tool.poetry]
name = "hiss"
version = "0.1.0"
description = "open source hackathon registration system"
authors = ["Gabriel Britain", "Cameron Brill <tamuhack@cameronbrill.me>", "Adil Rasiyani"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
autohooks = "^2.2.0"
autohooks-plugin-black = "^1.2.0"
autohooks-plugin-pylint = "^1.2.0"
autohooks-plugin-isort = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 80